name: Merge and Publish Builds

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      CSE305_ACTION_PAT:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: 1zumisagiri
          password: ${{ secrets.CSE305_ACTION_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ub-cse-305/305image
          tags: |
            type=raw,value=${{ inputs.version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.authors="Vincent Chan <vichan39@buffalo.edu>"
            org.opencontainers.image.title=CSE305 Intro to Programming Languages Course Image
            org.opencontainers.image.description=Provides Opam, OCaml, and Utop with a preconfigured Emacs development environment
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ inputs.version }}

      - name: Create multi-arch manifest and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create \
            -t ghcr.io/ub-cse-305/305image:${{ inputs.version }} \
            -t ghcr.io/ub-cse-305/305image:latest \
            $(printf 'ghcr.io/ub-cse-305/305image@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/ub-cse-305/305image:${{ inputs.version }}
          docker buildx imagetools inspect ghcr.io/ub-cse-305/305image:latest
