name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
    paths: [ "Dockerfile" ]
  workflow_dispatch:

jobs:
  version:
    uses: ./.github/workflows/version.yaml

  build:
    needs: version
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.version.outputs.version }}
    secrets:
      CSE305_ACTION_PAT: ${{ secrets.CSE305_ACTION_PAT }}

  merge:
    needs: [build, version]
    uses: ./.github/workflows/merge.yaml
    with:
      version: ${{ needs.version.outputs.version }}
    secrets:
      CSE305_ACTION_PAT: ${{ secrets.CSE305_ACTION_PAT }}
