name: Generate Version

on:
  workflow_call:
    outputs:
      version:
        description: "Generated version"
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setver.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate new version number from GHCR
        id: setver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PKG="305image"
          OWNER="ub-cse-305"

          ALL_TAGS=$(gh api /orgs/$OWNER/packages/container/$PKG/versions \
            -H "Accept: application/vnd.github+json" \
            | jq -r '
                .[]
                | .metadata.container.tags[]?
                | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))
            ')

          echo "All semantic version tags found:"
          echo "$ALL_TAGS"

          LAST_TAG=$(echo "$ALL_TAGS" | sort -V | tail -n1)
          if [[ -z "$LAST_TAG" ]]; then
            LAST_TAG="0.0.0"
          fi

          IFS='.' read -r MAJOR MINOR PATCH <<< "$LAST_TAG"
          PATCH=$((PATCH+1))
          VERSION="$MAJOR.$MINOR.$PATCH"

          echo "Generated version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
